---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

## Grant application  

### Instructions  
[Canada Graduate Scholarships-Master’s Program](http://www.nserc-crsng.gc.ca/students-etudiants/pg-cs/cgsm-bescm_eng.asp)  

[Actual instructions here if you choose to apply by Dec](http://www.nserc-crsng.gc.ca/ResearchPortal-PortailDeRecherche/Instructions-Instructions/CGS_M-BESC_M_eng.asp)  

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(knitr)
grant <- read_csv("BIOL3250_grant.csv")
knitr::kable(grant)
``` 

### Template   
A [**sample grant**](https://figshare.com/articles/online_resource/BIOL3250_grant_template/13224755) outlined with the formatting set up correctly for submission and for evaluation.   

### Resources    
[Ten simple rules for writing a career development award proposal](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005863)  

[Ten Simple Rules for Getting Grants](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.0020012)  

[Ten simple rules for short and swift presentations](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005373)   



