---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

## Module 2  

### Readings  


[Ten simple rules for writing a career development award proposal](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005863)  

[Ten Simple Rules for Getting Grants](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.0020012)  

[Ten simple rules for short and swift presentations](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005373)   

### Grant proposal  

**Marking key**  
Page 1.  
Title clear?  
Summary compelling and simple and plain language (< 1800 words)?  

Page 2.  
The research proposal - ONE page only - just like Canadian Government rules.  

Page 3.  
Literature cited (at least 5 studies published within last 5 years cited)  

**Elements /10%**  
Background info & Objectives  
Hypothesis  
Outline of experimental design approach-theoretical  
Methods  
Significance  

**Overview /10%**  
Have you presented a compelling case?  
Have you made your hypothesis explicit?  
Does your project seem feasible? Is it overly ambitious?   
Does it have other weaknesses?   
Have you stated the means that grantors can use to evaluate the success of your project after you have executed it? This means – have you stated the significance and/or outcome?  

**Background info**  
[Canada Graduate Scholarships-Master’s Program](http://www.nserc-crsng.gc.ca/students-etudiants/pg-cs/cgsm-bescm_eng.asp)  

[Actual instructions here if you choose to apply by Dec](http://www.nserc-crsng.gc.ca/ResearchPortal-PortailDeRecherche/Instructions-Instructions/CGS_M-BESC_M_eng.asp)

  



### Presentation  
20 slides x 20 seconds each.  total is 6.5 mins each.  
**Marking key**  
Please score each criterion on a Likert scale of 1 to 5 with 1 being poor and 5 being excellent.  

1. Relevance described    
2. Hypothesis & predictions    
3. Experimental Design   
4. How likely is this proposal to be funded?  

Total is 20% (out of 5 for each of above)  

Penalties  
a. slides unclear or hard to see  
b. timing too long or rushed  




